sudo: required
language: node_js
node_js:
  - "7"
cache: yarn
services:
  - docker

script:
  - yarn test
  - docker-compose run tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t jfernandes/e2e-frontend:$TRAVIS_BUILD_NUMBER .; 
    docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
    docker push jfernandes/e2e-frontend:$TRAVIS_BUILD_NUMBER;
    fi